### PR TITLE
fix(okdownload): sync stream runnable finishes in advance

### LINKED ISSUE #129: IOException: The current offset on block-info isn't update correct, 0 != 1797255 on 1
### OkDownload Version

v1.0.4-SNAPSHOT

### Problem Describe

I occur some problem, I also search on [issues][issues-url] and [wiki][wiki-url], I even checked the source code, but it can't help, so my real problem is:

`MultiPointOutputStream#inspectStreamState` has  a vulnerability causes `MultiPointOutputStream#syncRunnable` finishing in advance, and other blocks cannot do sync work. Finally, `IOException(The current offset on block-info isn't update correct, 0 != 1797255 on x)` will be thrown during `MultiPointOutputStream#inspectComplete`.

### Log

There is the whole log from LogCat when I occur the problem(I know we can use [this tool][okcat-wiki-url] to let log more readable):

```
20:48:16.667      CallbackDispatcher  D  -----> start trial task(1) {range=[bytes=0-0]}
20:48:17.047      CallbackDispatcher  D  <----- finish trial task(1) code[206]{accept-ranges=[bytes], access-control-allow-origin=[*], access-control-expose-headers=[X-Log, X-Reqid], access-control-max-age=[2592000], cache-control=[public, max-age=31536000, no-cache], content-disposition=[inline; filename="pt20180802p03.zip"; filename*=utf-8' 'pt20180802p03.zip], content-length=[1], content-range=[bytes 0-0/5391765], content-transfer-encoding=[binary], content-type=[application/zip], date=[Tue, 07 Aug 2018 12:48:12 GMT], expires=[0], server=[nginx], x-log=[mc.g;1s.gh:12;PFDS:13;AUTHPROXY_jjh_out:16;IO:17], x-qiniu-zone=[0], x-reqid=[hw8AAIjaU3n0E0cV], x-ser=[BC54_dx-lt-yd-shandong-jinan-5-cache-6, BC80_dx-jiangsu-yancheng-3-cache-8], x-svr=[IO]}
20:48:17.047      DownloadDispatcher  D  is file conflict after run: 1
20:48:17.049            DownloadCall  D  breakpoint invalid: download from beginning because of local check is dirty 1 fileExist[false] infoRight[false] outputStreamSupport[true] com.liulishuo.okdownload.core.d.a@1f7d142a
20:48:17.049      CallbackDispatcher  D  downloadFromBeginning: 1
20:48:17.050          FileDownloader  D  create a okhttp connection with https://cc-b.llscdn.com/ssk-prod/z/pt20180802p03.zip
20:48:17.050          FileDownloader  D  create a okhttp connection with https://cc-b.llscdn.com/ssk-prod/z/pt20180802p03.zip
20:48:17.051       HeaderInterceptor  D  AssembleHeaderRange (1) block(2) downloadFrom(3594510) currentOffset(0)
20:48:17.051      CallbackDispatcher  D  -----> start connection task(1) block(2) {range=[bytes=3594510-5391764], user-agent=[OkDownload/1.0.4-SNAPSHOT]}
20:48:17.051          ProgressAssist  D  contentLength: 5391765 callbackMinIntervalBytes: 89862
20:48:17.051       HeaderInterceptor  D  AssembleHeaderRange (1) block(0) downloadFrom(0) currentOffset(0)
20:48:17.053      CallbackDispatcher  D  -----> start connection task(1) block(0) {range=[bytes=0-1797254], user-agent=[OkDownload/1.0.4-SNAPSHOT]}
20:48:17.057          FileDownloader  D  create a okhttp connection with https://cc-b.llscdn.com/ssk-prod/z/pt20180802p03.zip
20:48:17.057       HeaderInterceptor  D  AssembleHeaderRange (1) block(1) downloadFrom(1797255) currentOffset(0)
20:48:17.057      CallbackDispatcher  D  -----> start connection task(1) block(1) {range=[bytes=1797255-3594509], user-agent=[OkDownload/1.0.4-SNAPSHOT]}
20:48:17.437      CallbackDispatcher  D  <----- finish connection task(1) block(2) code[206]{accept-ranges=[bytes], access-control-allow-origin=[*], access-control-expose-headers=[X-Log, X-Reqid], access-control-max-age=[2592000], cache-control=[public, max-age=31536000, no-cache], content-disposition=[inline; filename="pt20180802p03.zip"; filename*=utf-8' 'pt20180802p03.zip], content-length=[1797255], content-range=[bytes 3594510-5391764/5391765], content-transfer-encoding=[binary], content-type=[application/zip], date=[Tue, 07 Aug 2018 12:48:13 GMT], expires=[0], server=[nginx], x-log=[mc.g;1s.gh:12;PFDS:13;AUTHPROXY_jjh_out:16;IO:17], x-qiniu-zone=[0], x-reqid=[hw8AAIjaU3n0E0cV], x-ser=[BC54_dx-lt-yd-shandong-jinan-5-cache-6, BC80_dx-jiangsu-yancheng-3-cache-8], x-svr=[IO]}
20:48:17.437      CallbackDispatcher  D  fetchStart: 1
20:48:17.439      CallbackDispatcher  D  <----- finish connection task(1) block(0) code[206]{accept-ranges=[bytes], access-control-allow-origin=[*], access-control-expose-headers=[X-Log, X-Reqid], access-control-max-age=[2592000], cache-control=[public, max-age=31536000, no-cache], content-disposition=[inline; filename="pt20180802p03.zip"; filename*=utf-8' 'pt20180802p03.zip], content-length=[1797255], content-range=[bytes 0-1797254/5391765], content-transfer-encoding=[binary], content-type=[application/zip], date=[Tue, 07 Aug 2018 12:48:13 GMT], expires=[0], server=[nginx], x-log=[mc.g;1s.gh:12;PFDS:13;AUTHPROXY_jjh_out:16;IO:17], x-qiniu-zone=[0], x-reqid=[hw8AAIjaU3n0E0cV], x-ser=[BC54_dx-lt-yd-shandong-jinan-5-cache-6, BC80_dx-jiangsu-yancheng-3-cache-8], x-svr=[IO]}
20:48:17.439      CallbackDispatcher  D  fetchStart: 1
20:48:17.446  MultiPointOutputStream  D  Create new file: data.zip
20:48:17.471  MultiPointOutputStream  D  OutputStream start flush looper task[1] with syncBufferIntervalMills[2000] syncBufferSize[65536]
20:48:17.476      CallbackDispatcher  D  <----- finish connection task(1) block(1) code[206]{accept-ranges=[bytes], access-control-allow-origin=[*], access-control-expose-headers=[X-Log, X-Reqid], access-control-max-age=[2592000], cache-control=[public, max-age=31536000, no-cache], content-disposition=[inline; filename="pt20180802p03.zip"; filename*=utf-8' 'pt20180802p03.zip], content-length=[1797255], content-range=[bytes 1797255-3594509/5391765], content-transfer-encoding=[binary], content-type=[application/zip], date=[Tue, 07 Aug 2018 12:48:13 GMT], expires=[0], server=[nginx], x-log=[mc.g;1s.gh:12;PFDS:13;AUTHPROXY_jjh_out:16;IO:17], x-qiniu-zone=[0], x-reqid=[hw8AAIjaU3n0E0cV], x-ser=[BC54_dx-lt-yd-shandong-jinan-5-cache-6, BC80_dx-jiangsu-yancheng-3-cache-8], x-svr=[IO]}
20:48:17.476      CallbackDispatcher  D  fetchStart: 1
20:48:17.596  MultiPointOutputStream  D  OutputStream sync success (1) block(0)  syncLength(48237) currentOffset(48237)
20:48:19.624  MultiPointOutputStream  D  OutputStream sync success (1) block(0)  syncLength(745472) currentOffset(793709)
20:48:20.799  MultiPointOutputStream  D  runSync state change isNoMoreStream[true] newNoMoreStreamBlockList[[0]]
20:48:20.809  MultiPointOutputStream  D  Create output stream write from (1) block(1) 1797255
20:48:20.825  MultiPointOutputStream  D  OutputStream sync success (1) block(0)  syncLength(1003546) currentOffset(1797255)
20:48:20.826  MultiPointOutputStream  D  OutputStream close task[1] block[0]
20:48:20.826      CallbackDispatcher  D  fetchEnd: 1
20:48:20.826           DownloadChain  D  release connection com.liulishuo.okdownload.core.b.b@16b9ff64 task[1] block[0]
20:48:22.953  MultiPointOutputStream  D  Create output stream write from (1) block(2) 3594510
20:48:23.016  MultiPointOutputStream  D  OutputStream done but no need to ensure sync, because the syncFuture.isDone[true] task[1] block[1]
20:48:23.018  MultiPointOutputStream  D  OutputStream close task[1] block[1]
20:48:23.020           DownloadCache  D  catch unknown error java.io.IOException: The current offset on block-info isn't update correct, 0 != 1797255 on 1
20:48:23.021           DownloadChain  D  release connection com.liulishuo.okdownload.core.b.b@45a65cd task[1] block[1]
20:48:23.229  MultiPointOutputStream  D  OutputStream done but no need to ensure sync, because the syncFuture.isDone[true] task[1] block[2]
20:48:23.230  MultiPointOutputStream  D  OutputStream close task[1] block[2]
20:48:23.231      CallbackDispatcher  D  taskEnd: 1 ERROR java.io.IOException: The current offset on block-info isn't update correct, 0 != 1797255 on 1
```
The pivotal log is:
```
20:48:20.799  MultiPointOutputStream  D  runSync state change isNoMoreStream[true] newNoMoreStreamBlockList[[0]]
20:48:20.809  MultiPointOutputStream  D  Create output stream write from (1) block(1) 1797255
20:48:20.825  MultiPointOutputStream  D  OutputStream sync success (1) block(0)  syncLength(1003546) currentOffset(1797255)
20:48:20.826  MultiPointOutputStream  D  OutputStream close task[1] block[0]
20:48:20.826      CallbackDispatcher  D  fetchEnd: 1
20:48:20.826           DownloadChain  D  release connection com.liulishuo.okdownload.core.b.b@16b9ff64 task[1] block[0]
20:48:22.953  MultiPointOutputStream  D  Create output stream write from (1) block(2) 3594510
```
The first log above indicates that there are no more streams in this download task and then the `MultiPointOutputStream#syncRunnable` will be end. This is because that there is just one OutputStream in `MultiPointOutputStream#outputStreamMap` and the other two are not been created, we can confirm that from log with time `20:48:20.809` and `20:48:22.953`.

I think `MultiPointOutputStream#inspectStreamState` is not correct and I will send a pull request to solve this problem later.

[issues-url]: https://github.com/lingochamp/okdownload/issues
[wiki-url]: https://github.com/lingochamp/okdownload/wiki
[okcat-wiki-url]: https://github.com/lingochamp/okdownload/wiki/Debug-OkDownload

### PR DESCRIPTION
**Pull request by rantianhua**
Closes #129

### CODE REVIEW

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 1]
```diff
@@ -299,6 +301,15 @@ void inspectStreamState(StreamsState state) {
         boolean isNoMoreStream = true;
         state.newNoMoreStreamBlockList.clear();
 
+        final int totalBlockCount = info.getBlockCount();
+        final int outputStreamCreatedBlockCount = outputStreamCreatedBlockCounter.get();
```
Comment (Jacksgong) [inline okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: the count of `outputStream` will accept to not equal to the `totalBlockCount` when some blocks have been finished before download this time.

Comment (Jacksgong) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: One another case, when a connection is failed or even not finish connect, it's also accepted `not equal`.

**Comment by Jacksgong** [comment]
The pre-logic about `isNoMoreStream` just dependent on have created and working stream completed which really have one problem, it only can be raised when on the one gap all working streams are completed downloading, but there is still another block just finish connect and just start to create a stream to accept incoming data, but `runSync` looper has been finished because all pre-working streams are finished, so there is no chance for it to write data to database.

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java (hunk 1 above)
Comment (rantianhua) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: updated

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 2]
```diff
@@ -71,13 +72,16 @@
     volatile Future syncFuture;
     volatile Thread runSyncThread;
     final SparseArray<Thread> parkedRunBlockThreadMap = new SparseArray<>();
+    final AtomicInteger outputStreamCreatedBlockCounter = new AtomicInteger(0);
```
Comment (Jacksgong) [inline okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: Use `NoMoreStreamList` can handle the same ting.

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 3]
```diff
@@ -71,13 +72,16 @@
...
 
     @NonNull private final Runnable syncRunnable;
     private String path;
 
     IOException syncException;
     @NonNull List<Integer> noMoreStreamList;
 
+    int currentNeedFetchBlockCount;
```
Comment (Jacksgong) [inline okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: Please just use `needFetchBlockCount` as the param name.

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 4]
```diff
@@ -299,6 +303,14 @@ void inspectStreamState(StreamsState state) {
         boolean isNoMoreStream = true;
         state.newNoMoreStreamBlockList.clear();
 
+        final int outputStreamCreatedBlockCount = outputStreamCreatedBlockCounter.get();
+        if (outputStreamCreatedBlockCount != currentNeedFetchBlockCount) {
```
Comment (Jacksgong) [inline okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: You can feel free to compare with `NoMoreStreamList`.

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 5]
```diff
@@ -413,6 +420,8 @@ void runSync() throws IOException {
             flushProcess();
             nextParkMills = syncBufferIntervalMills;
         }
+
+        Util.d(TAG, "IO sync end");
```
Comment (Jacksgong) [inline okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: You know, here is the loop of sync process to breakpoint-store end, not I/O sync.

File: okdownload/src/main/java/com/liulishuo/okdownload/core/interceptor/RetryInterceptor.java [hunk 6]
```diff
@@ -45,6 +45,9 @@
                 }
 
                 chain.getCache().catchException(e);
+                if (e != InterruptException.SIGNAL) {
```
Comment (Jacksgong) [inline okdownload/src/main/java/com/liulishuo/okdownload/core/interceptor/RetryInterceptor.java]: It's no need to except `InterruptException.SIGNAL`, because it will let `catchBlockConnectException` method decoupling with the case of `InterruptException`, and on the logic design, it's fine to catch all `IOException` on the internal of `catchBlockConnectException`

Comment (rantianhua) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/interceptor/RetryInterceptor.java]: But `catchBlockConnectException ` will be invoked multi times if don't except InterruptException.SIGNAL, that will cause the size of noMoreStreamList larger than needFetchBlockCount

Comment (rantianhua) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/interceptor/RetryInterceptor.java]: Or, I can handle duplicate logic in `catchBlockConnectException` method so that decoupling with the case of `InterruptException `.

Comment (rantianhua) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/interceptor/RetryInterceptor.java]: updated

Comment (Jacksgong) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/interceptor/RetryInterceptor.java]: 1. Please don't trust the count of `noMoreStreamList`, it will contain same block-index duplicate, and it is accepted. the `noMoreStreamList` is just can tell which one is `no-more-stream`.
2. If you rely on the `catchBlockConnectException` can be only invoked once, it's very bad design
3. For the current block-thread, I don't think this will be invoked more than once

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 7]
```diff
@@ -303,7 +303,10 @@ void inspectStreamState(StreamsState state) {
         boolean isNoMoreStream = true;
         state.newNoMoreStreamBlockList.clear();
 
-        final int outputStreamCreatedBlockCount = noMoreStreamList.size();
+        @SuppressWarnings("unchecked")
+        final List<Integer> outputStreamCreatedBlockList = (List<Integer>) noMoreStreamList.clone();
```
Comment (Jacksgong) [inline okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: `outputStreamcreatedBlockList` not really equal to `noMoreStreamList`, you can use `clonedList`.

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 8]
```diff
@@ -303,7 +303,10 @@ void inspectStreamState(StreamsState state) {
...
+        final Set<Integer> uniqueBlockList = new HashSet<>(outputStreamCreatedBlockList);
+        final int outputStreamCreatedBlockCount = uniqueBlockList.size();
```
Comment (Jacksgong) [inline okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: please consider `noMoreStreamBlockCount`

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 9]
```diff
@@ -299,6 +303,21 @@ void inspectStreamState(StreamsState state) {
         boolean isNoMoreStream = true;
```
[the remark this answers is not in the document]
Comment (rantianhua) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: updated

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 10]
```diff
@@ -299,6 +303,21 @@ void inspectStreamState(StreamsState state) {
...
 
+        @SuppressWarnings("unchecked")
+        final List<Integer> clonedList = (List<Integer>) noMoreStreamList.clone();
+        final Set<Integer> uniqueBlockList = new HashSet<>(clonedList);
+        final int noMoreStreamBlockCount = uniqueBlockList.size();
+        if (noMoreStreamBlockCount != needFetchBlockCount) {
+            Util.d(TAG, "current need fetch block count " + needFetchBlockCount
+                    + " is not equal to output stream created block count "
+                    + noMoreStreamBlockCount);
+            isNoMoreStream = false;
```
[the remark this answers is not in the document]
Comment (rantianhua) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: updated

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 11]
```diff
@@ -299,6 +303,21 @@ void inspectStreamState(StreamsState state) {
...
+        } else {
+            Util.d(TAG, "current need fetch block count " + needFetchBlockCount
+                    + " is equal to output stream created block count "
+                    + noMoreStreamBlockCount);
```
[the remark this answers is not in the document]
Comment (rantianhua) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: updated

File: okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java [hunk 12]
```diff
@@ -76,7 +78,9 @@
     private String path;
 
     IOException syncException;
-    @NonNull List<Integer> noMoreStreamList;
+    @NonNull ArrayList<Integer> noMoreStreamList;
+
+    int needFetchBlockCount;
```
[the remark this answers is not in the document]
Comment (rantianhua) [reply okdownload/src/main/java/com/liulishuo/okdownload/core/file/MultiPointOutputStream.java]: updated
